update trunk configuration

diff --git a/trunk b/trunk
--- a/trunk
+++ b/trunk
@@ -8,7 +8,7 @@
 
 set -euo pipefail
 
-readonly TRUNK_LAUNCHER_VERSION="1.2.1"  # warning: this line is auto-updated
+readonly TRUNK_LAUNCHER_VERSION="1.2.7" # warning: this line is auto-updated
 
 readonly SUCCESS_MARK="\033[0;32m✔\033[0m"
 readonly FAIL_MARK="\033[0;31m✘\033[0m"
@@ -17,13 +17,17 @@ readonly PROGRESS_MARKS=("⡿" "⢿" "⣻" "⣽" "⣾" "⣷" "⣯" "⣟")
 # This is how mktemp(1) decides where to create stuff in tmpfs.
 readonly TMPDIR="${TMPDIR:-/tmp}"
 
-readonly CLI_DIR="${HOME}/.cache/trunk/cli"
-mkdir -p "${CLI_DIR}"
-
 KERNEL=$(uname | tr "[:upper:]" "[:lower:]")
+if [[ ${KERNEL} == mingw64* || ${KERNEL} == msys* ]]; then
+  KERNEL="mingw"
+fi
 readonly KERNEL
 
 MACHINE=$(uname -m)
+if [[ $MACHINE == "aarch64" ]]; then
+  MACHINE="arm64";
+fi
+
 readonly MACHINE
 
 PLATFORM="${KERNEL}-${MACHINE}"
@@ -37,13 +41,29 @@ readonly PLATFORM_UNDERSCORE
 # [0K is "erase display" and clears from the cursor to the end of the screen
 readonly CLEAR_LAST_MSG="\033[1F\033[0K"
 
-# NOTE(sam): TRUNK_LAUNCHER_QUIET was originally TRUNK_QUIET; it was renamed after 0.7.0-beta.9
-readonly TRUNK_LAUNCHER_QUIET=${TRUNK_LAUNCHER_QUIET:-${TRUNK_QUIET:-false}}
+if [[ ! -z ${CI:-} && "${CI}" = true && -z ${TRUNK_LAUNCHER_QUIET:-} ]]; then
+  TRUNK_LAUNCHER_QUIET=1
+else
+  TRUNK_LAUNCHER_QUIET=${TRUNK_LAUNCHER_QUIET:-${TRUNK_QUIET:-false}}
+fi
+
 readonly TRUNK_LAUNCHER_DEBUG
 
 if [[ ${TRUNK_LAUNCHER_QUIET} != false ]]; then
   exec 3>&1 4>&2 &>/dev/null
 fi
+
+TRUNK_CACHE="${TRUNK_CACHE:-}"
+if [[ -n ${TRUNK_CACHE} ]]; then
+  :
+elif [[ -n ${XDG_CACHE_HOME:-} ]]; then
+  TRUNK_CACHE="${XDG_CACHE_HOME}/trunk"
+else
+  TRUNK_CACHE="${HOME}/.cache/trunk"
+fi
+readonly TRUNK_CACHE
+readonly CLI_DIR="${TRUNK_CACHE}/cli"
+mkdir -p "${CLI_DIR}"
 
 # platform check
 readonly MINIMUM_MACOS_VERSION="10.15"
@@ -52,28 +72,32 @@ check_darwin_version() {
   osx_version="$(sw_vers -productVersion)"
 
   # trunk-ignore-begin(shellcheck/SC2312): the == will fail if anything inside the $() fails
-  if [[ "$(printf "%s\n%s\n" "${MINIMUM_MACOS_VERSION}" "${osx_version}" | \
-           sort --version-sort | \
-           head -n 1)" == "${MINIMUM_MACOS_VERSION}"* ]]; then
+  if [[ "$(printf "%s\n%s\n" "${MINIMUM_MACOS_VERSION}" "${osx_version}" |
+    sort --version-sort |
+    head -n 1)" == "${MINIMUM_MACOS_VERSION}"* ]]; then
     return
   fi
   # trunk-ignore-end(shellcheck/SC2312)
 
   echo -e "${FAIL_MARK} Trunk requires at least MacOS ${MINIMUM_MACOS_VERSION}" \
-          "(yours is ${osx_version}). See https://docs.trunk.io for more info."
+    "(yours is ${osx_version}). See https://docs.trunk.io for more info."
   exit 1
 }
+
 if [[ ${PLATFORM} == "darwin-x86_64" || ${PLATFORM} == "darwin-arm64" ]]; then
   check_darwin_version
-elif [[ ${PLATFORM} == "linux-x86_64" ]]; then
+elif [[ ${PLATFORM} == "linux-x86_64" || ${PLATFORM} == "linux-arm64" || ${PLATFORM} == "windows-x86_64" || ${PLATFORM} == "mingw-x86_64" ]]; then
   :
 else
-  echo -e "${FAIL_MARK} Trunk is only supported on Linux (x64_64) and MacOS (x86_64, arm64)." \
-          "See https://docs.trunk.io for more info."
+  echo -e "${FAIL_MARK} Trunk is only supported on Linux (x64_64, arm64), MacOS (x86_64, arm64), and Windows (x86_64)." \
+    "See https://docs.trunk.io for more info."
   exit 1
 fi
 
-TRUNK_TMPDIR="${TMPDIR}/trunk-$(set -e; id -u)/launcher_logs"
+TRUNK_TMPDIR="${TMPDIR}/trunk-$(
+  set -e
+  id -u
+)/launcher_logs"
 readonly TRUNK_TMPDIR
 mkdir -p "${TRUNK_TMPDIR}"
 
@@ -83,7 +107,7 @@ readonly TOOL_TMPDIR
 
 cleanup() {
   rm -rf "${TOOL_TMPDIR}"
-  if [[ "$1" == "0" ]]; then
+  if [[ $1 == "0" ]]; then
     rm -rf "${TRUNK_TMPDIR}"
   fi
 }
@@ -121,14 +145,20 @@ awk_test() {
   # trunk-ignore-begin(shellcheck/SC2310,shellcheck/SC2312)
   # SC2310 and SC2312 are about set -e not propagating to the $(); if that happens, the string
   # comparison will fail and we'll claim the user's awk doesn't work
-  if [[ $(set -e; printf 'k1: v1\n \tk2: v2\r\n'   | lawk '/[ \t]+k2:/{print $2}') == 'v2' && \
-        $(set -e; printf 'k1: v1\r\n\t k2: v2\r\n' | lawk '/[ \t]+k2:/{print $2}') == 'v2' ]]; then
+  if [[ $(
+    set -e
+    printf 'k1: v1\n \tk2: v2\r\n' | lawk '/[ \t]+k2:/{print $2}'
+  ) == 'v2' &&
+  $(
+    set -e
+    printf 'k1: v1\r\n\t k2: v2\r\n' | lawk '/[ \t]+k2:/{print $2}'
+  ) == 'v2' ]]; then
     return
   fi
   # trunk-ignore-end(shellcheck/SC2310,shellcheck/SC2312)
 
   echo -e "${FAIL_MARK} Trunk does not work with your awk;" \
-          "please report this at https://slack.trunk.io."
+    "please report this at https://slack.trunk.io."
   echo -e "Your version of awk is:"
   awk --version || awk -Wversion
   exit 1
@@ -137,7 +167,10 @@ awk_test
 
 readonly CURL_FLAGS="${CURL_FLAGS:- -vvv --max-time 120 --retry 3 --fail}"
 readonly WGET_FLAGS="${WGET_FLAGS:- --verbose --tries=3 --limit-rate=10M}"
-TMP_DOWNLOAD_LOG="${TRUNK_TMPDIR}/download-$(set -e; dt_str).log"
+TMP_DOWNLOAD_LOG="${TRUNK_TMPDIR}/download-$(
+  set -e
+  dt_str
+).log"
 readonly TMP_DOWNLOAD_LOG
 
 # Detect whether we should use wget or curl.
@@ -211,22 +244,25 @@ download_url() {
   while [[ -d "/proc/${download_pid}" && -n ${progress_message} ]]; do
     echo -e "${CLEAR_LAST_MSG}${PROGRESS_MARKS[${i_prog}]} ${progress_message}..."
     sleep 0.2
-    i_prog=$(( (i_prog + 1) % ${#PROGRESS_MARKS[@]} ))
+    i_prog=$(((i_prog + 1) % ${#PROGRESS_MARKS[@]}))
   done
 
   local download_log
   if ! wait "${download_pid}"; then
-    download_log="${TRUNK_TMPDIR}/launcher-download-$(set -e; dt_str).log"
+    download_log="${TRUNK_TMPDIR}/launcher-download-$(
+      set -e
+      dt_str
+    ).log"
     mv "${TMP_DOWNLOAD_LOG}" "${download_log}"
     echo -e "${CLEAR_LAST_MSG}${FAIL_MARK} ${progress_message}... FAILED (see ${download_log})"
     echo -e "Please check your connection and try again." \
-            "If you continue to see this error message," \
-            "consider reporting it to us at https://slack.trunk.io."
+      "If you continue to see this error message," \
+      "consider reporting it to us at https://slack.trunk.io."
     exit 1
   fi
 
   if [[ -n ${progress_message} ]]; then
-   echo -e "${CLEAR_LAST_MSG}${SUCCESS_MARK} ${progress_message}... done"
+    echo -e "${CLEAR_LAST_MSG}${SUCCESS_MARK} ${progress_message}... done"
   fi
 
 }
@@ -267,10 +303,13 @@ read_cli_version_from() {
   local config_abspath="${1}"
   local cli_version
 
-  cli_version="$(set -e; lawk '/[ \t]+version:/{print $2; exit;}' "${config_abspath}")"
+  cli_version="$(
+    set -e
+    lawk '/[ \t]+version:/{print $2; exit;}' "${config_abspath}"
+  )"
   if [[ -z ${cli_version} ]]; then
     echo -e "${FAIL_MARK} Invalid .trunk/trunk.yaml, no cli version found." \
-            "See https://docs.trunk.io for more info." >&2
+      "See https://docs.trunk.io for more info." >&2
     exit 1
   fi
 
@@ -289,11 +328,11 @@ download_cli() {
   if sort --help 2>&1 | grep BusyBox; then
     readonly URL="https://trunk.io/releases/${dl_version}/trunk-${dl_version}-${PLATFORM}.tar.gz"
   else
-    if [[ "$(printf "%s\n%s\n" "${TRUNK_NEW_URL_VERSION}" "${dl_version}" | \
-            sort --version-sort | \
-            head -n 1)" == "${TRUNK_NEW_URL_VERSION}"* ]]; then
+    if [[ "$(printf "%s\n%s\n" "${TRUNK_NEW_URL_VERSION}" "${dl_version}" |
+      sort --version-sort |
+      head -n 1 || true)" == "${TRUNK_NEW_URL_VERSION}"* ]]; then
       readonly URL="https://trunk.io/releases/${dl_version}/trunk-${dl_version}-${PLATFORM}.tar.gz"
-      else
+    else
       readonly URL="https://trunk.io/releases/trunk-${dl_version}.${KERNEL}.tar.gz"
     fi
   fi
@@ -306,7 +345,10 @@ download_cli() {
     local verifying_text="Verifying Trunk sha256..."
     echo -e "${PROGRESS_MARKS[0]} ${verifying_text}"
 
-    actual_sha256="$(set -e; sha256sum "${DOWNLOAD_TAR_GZ}" | lawk '{print $1}')"
+    actual_sha256="$(
+      set -e
+      sha256sum "${DOWNLOAD_TAR_GZ}" | lawk '{print $1}'
+    )"
 
     if [[ ${actual_sha256} != "${expected_sha256}" ]]; then
       echo -e "${CLEAR_LAST_MSG}${FAIL_MARK} ${verifying_text} FAILED"
@@ -331,7 +373,7 @@ download_cli() {
   if [[ ! -e ${OLD_TOOL_DIR} ]]; then
     ln -sf "${TOOL_PART}" "${OLD_TOOL_DIR}"
   fi
-  mv -n "${TMP_INSTALL_DIR}/trunk" "${TOOL_DIR}/"
+  mv -n "${TMP_INSTALL_DIR}/trunk" "${TOOL_DIR}/" || true
   rm -rf "${TMP_INSTALL_DIR}"
 }
 
@@ -341,47 +383,43 @@ download_cli() {
 #                                                                             #
 ###############################################################################
 
-CONFIG_ABSPATH="$(set -e; trunk_yaml_abspath)"
+CONFIG_ABSPATH="$(
+  set -e
+  trunk_yaml_abspath
+)"
 readonly CONFIG_ABSPATH
 
 version="${TRUNK_CLI_VERSION:-}"
 if [[ -n ${version:-} ]]; then
   :
 elif [[ -f ${CONFIG_ABSPATH} ]]; then
-  version="$(set -e; read_cli_version_from "${CONFIG_ABSPATH}")"
-  version_sha256="$(set -e; lawk "/${PLATFORM_UNDERSCORE}:/"'{print $2}' "${CONFIG_ABSPATH}")"
+  version="$(
+    set -e
+    read_cli_version_from "${CONFIG_ABSPATH}"
+  )"
+  version_sha256="$(
+    set -e
+    lawk "/${PLATFORM_UNDERSCORE}:/"'{print $2}' "${CONFIG_ABSPATH}"
+  )"
 else
   readonly LATEST_FILE="${LAUNCHER_TMPDIR}/latest"
   download_url "https://trunk.io/releases/latest" "${LATEST_FILE}"
-  version=$(set -e; lawk '/version:/{print $2}' "${LATEST_FILE}")
-  version_sha256=$(set -e; lawk "/${PLATFORM_UNDERSCORE}:/"'{print $2}' "${LATEST_FILE}")
+  version=$(
+    set -e
+    lawk '/version:/{print $2}' "${LATEST_FILE}"
+  )
+  version_sha256=$(
+    set -e
+    lawk "/${PLATFORM_UNDERSCORE}:/"'{print $2}' "${LATEST_FILE}"
+  )
 fi
 
 readonly TOOL_PART="${version}-${PLATFORM}"
 readonly TOOL_DIR="${CLI_DIR}/${TOOL_PART}"
 
 if [[ ! -e ${TOOL_DIR}/trunk ]]; then
-  if [[ ${TRUNK_LAUNCHER_QUIET} == false && -n ${LATEST_FILE:-} ]]; then
-    read -rp "Would you like to download and run the latest version of trunk? (Y/n) " yn
-    case "${yn}" in
-    Yes | yes | Y | y | "") ;;
-    *) exit 1 ;;
-    esac
-  fi
-
   download_cli "${version}" "${version_sha256:-}"
-
-  # It looks better to have whitespace between the launcher download steps and the CLI invocation:
-  #
-  #   $ trunk check
-  #   ✔ Downloading Trunk 0.7.0-beta... done
-  #   ✔ Verifying Trunk sha256... done
-  #   ✔ Unpacking Trunk... done
-  #
-  #   Checking 100% [=============================================>]  30/30  1.4s
-  #
-  # so we insert an echo here
-  echo
+  echo # add newline between launcher and CLI output
 fi
 
 if [[ ${TRUNK_LAUNCHER_QUIET} != false ]]; then
@@ -395,7 +433,7 @@ fi
 ###############################################################################
 
 if [[ -n ${LATEST_FILE:-} ]]; then
-  mv -n "${LATEST_FILE}" "${TOOL_DIR}/version"
+  mv -n "${LATEST_FILE}" "${TOOL_DIR}/version" >/dev/null 2>&1 || true
 fi
 
 # NOTE: exec will overwrite the process image, so trap will not catch the exit signal.
